######################################################
#                                                    #
#                 General Settings                   #
#                                                    #
######################################################

# Impostare i ruoli nel seguente modo per
# i ruoli da sincronizzare con discord
#
#  roles:
#    <in-game name role>: <discord id>
#    <in-game name role>: <discord id>
#
# Rimuovi il commento alla riga seguente per usare
#roles:


######################################################
#                                                    #
#                BungeeCord Settings                 #
#                                                    #
######################################################

# Comandi che vengono eseguiti quando un giocatore si linka
# Placeholders
# %player% --> nome del giocatore
# %group% --> eventuale gruppo da aggiungere
link-commands:
  - "lp user %player% parent add %group%"

# Comando per aggiungere un gruppo
# Placeholders
# %player% --> nome del giocatore
# %group% --> eventuale gruppo da aggiungere
addGroupCommand: "lp user %player% parent add %group%"

# Comando per rimuovere un gruppo
# Placeholders
# %player% --> nome del giocatore
# %group% --> eventuale gruppo da aggiungere
removeGroupCommand: "lp user %player% parent remove %group%"

# Configurazione chat e console
# chats:
#   <bungeecord server name>: <discord chat id>
#
# Rimuovi il commento per usare
#chats:


######################################################
#                                                    #
#               Discord Bot Settings                 #
#                                                    #
######################################################

# Inserisci qui il token bot
token-bot: "empty"

# Impostazioni pannello discord
link-panel:
  # Id della camera dove inviare il pannello
  channelid: "empty"
  messageid: "empty"
  link-emoji: "U+2705"
  sync-emoji: "U+2B55"

# Categoria dove vengono create le camere per il linking
category-link-id: "empty"

# Ruolo staff che può vedere i canali dei player che si devono linkare
staff-role: "empty"

# Inserisci qui l'id del ruolo che vuoi dare ai player quando si linkano
link-role-id: "empty"

# Messaggio che viene inviato nella camera dove il giocatore deve linkarsi
link-player-message: "%mention% invia il tuo nickname di minecraft per linkarti. \\nAttenzione: Per poterti verificare devi essere entrato almeno una volta nel server minecraft"

# Username non trovato
invalid-username: "Il tuo username non è tra i giocatori del server. Riprova"

# User reiatsu
# %amount% --> quantità reiatsu
discord-reiatsu: "Hai %amount% reiatsu"

# Permesso negato su discord
discord-no-permission: "Non hai il permesso di eseguire questo comando. Non sei un amministratore"

# Utente non trovato su discord
discord-user-not-found: "Utente non trovato"

# Mostra user reiatsu
# %user% nickname utente
# %amount% reiatsu utente
other-discord-reiatsu: "%user% ha %amount% reiatsu"


######################################################
#                                                    #
#              Pterodactyl Settings                  #
#                                                    #
######################################################

# Inserisci qui l'url del tuo pannello pterodactyl
ptero-url: "empty"

# Inserisci qui la client api key
ptero-api-key: "empty"

# Impostare i server nel seguente modo per
# far eseguire i comandi
#
#  servers:
#    - <pterodactyl server id 1>
#    - <pterodactyl server id 2>
#
# Rimuovi il commento alla riga seguente per usare
#servers:

