######################################################
#                                                    #
#                 General Settings                   #
#                                                    #
######################################################

# Impostare i ruoli nel seguente modo per
# i ruoli da sincronizzare con discord
#
#  roles:
#    <in-game name role>: <discord id>
#    <in-game name role>: <discord id>
#
# Rimuovi il commento alla riga seguente per usare
#roles:


######################################################
#                                                    #
#                BungeeCord Settings                 #
#                                                    #
######################################################

# Comandi che vengono eseguiti quando un giocatore si linka
# Placeholders
# %player% --> nome del giocatore
# %group% --> eventuale gruppo da aggiungere
link-commands:
  - "lp user %user% parent add %group%"

# Comandi che vengono eseguiti quando un giocatore si unlinka
# Placeholders
# %player% --> nome del giocatore
# %group% --> eventuale gruppo da aggiungere
unlink-commands:
  - "lp user %user% parent remove %group%"


# Comando per aggiungere un gruppo
# Placeholders
# %player% --> nome del giocatore
# %group% --> eventuale gruppo da aggiungere
addGroupCommand: "lp user %player% parent add %group%"

# Comando per rimuovere un gruppo
# Placeholders
# %player% --> nome del giocatore
# %group% --> eventuale gruppo da aggiungere
removeGroupCommand: "lp user %player% parent remove %group%"


######################################################
#                                                    #
#               Discord Bot Settings                 #
#                                                    #
######################################################

# Inserisci qui il token bot
token-bot: "empty"

# Impostazioni pannello discord
link-panel:
  # Id della camera dove inviare il pannello
  channelid: "empty"
  messageid: "empty"
  link-emoji: "white_check_mark"
  sync-emoji: "cyclone"


######################################################
#                                                    #
#              Pterodactyl Settings                  #
#                                                    #
######################################################

# Inserisci qui l'url del tuo pannello pterodactyl
ptero-url: "empty"

# Inserisci qui l'application api key
ptero-api-key: "empty"

# Impostare i server nel seguente modo per
# far eseguire i comandi
#
#  servers:
#    - <pterodactyl server id 1>
#    - <pterodactyl server id 2>
#
# Rimuovi il commento alla riga seguente per usare
#servers: